name: GitHub Classroom Workflow

on:
  push:
    branches:
      - 'main'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: self-hosted 
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - name: Autograder
        id: autograder
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: 'Part 1: Chain Length = 64, Unroll Factor = 1, Sequential'
          setup: "cp $HOME/cse113-autograder/hw1/part1/main.py part1",
          run: "python3 part1/main.py 64 1 0",
          comparison: "included",
          timeout: 10,
          points: 1